ICAO_abbr = {
    'Instrument flight rules': 'IFR',
    'Instrument landing system': 'ILS',
    'Maximum takeoff weight': 'MTOW',
    'Maximum takeoff mass': 'MTOM',
    'Maximum total weight authorized': 'MTWA',
    'Hong Kong International Airport': 'HKG',
    'Visual flight rules': 'VFR',
    'Air-to-air': 'A/A',
    'Air-to-ground': 'A/G',
    'Above Aerodrome Level': 'AAL',
    'Abeam': 'ABM',
    'Aerodrome Beacon': 'ABN',
    'About': 'ABT',
    'Above': 'ABV',
    'Area Control': 'ACC',
    'Aircraft': 'ACFT',
    'Acknowledge': 'ACK',
    'Altimeter Check Location': 'ACL',
    'Aircraft Classification Number': 'ACN',
    'Accepted': 'ACPT',
    'Active': 'ACT',
    'Aerodrome': 'AD',
    'Advisory Area': 'ADA',
    'Aerodrome Chart': 'ADC',
    'Additional': 'ADDN',
    'Adjacent': 'ADJ',
    'Advisory Route': 'ADR',
    'Automatic Dependent Surveillance': 'ADS',
    'Advisory Service': 'ADVS',
    'Advised': 'ADZ',
    'Flight Plan Filed In The Air': 'AFIL',
    'Affirm': 'AFM',
    'After': 'AFT',
    'Aerodromes, Air Routes and Ground Aids': 'AGA',
    'Again': 'AGN',
    'Alert Phase': 'ALERFA',
    'Alerting Service': 'ALRS',
    'Approach Lighting System': 'ALS',
    'Altitude': 'ALT',
    'Alternate': 'ALTN',
    'Area Minimum Altitude': 'AMA',
    'Aeronautical Chart': 'ANC',
    'Aeronautical Navigation Chart': 'ANCS',
    'Answer': 'ANS',
    'Aerodrome Obstacle Chart': 'AOC',
    'Airport': 'AP',
    'Approach': 'APCH',
    'Aircraft Parking/docking Chart': 'APDC',
    'Apron': 'APN',
    'Aprons': 'APNS',
    'Approach Control': 'APP',
    'April': 'APR',
    'Approximately': 'APRX',
    'After Passing': 'APSG',
    'Approved': 'APV',
    'Area Chart': 'ARC',
    'Arrange': 'ARNG',
    'Air Traffic Services Reporting Office': 'ARO',
    'Aerodrome Reference Point': 'ARP',
    'Arriving': 'ARR',
    'Arresting': 'ARST',
    'Ascend To': 'ASC',
    'Accelerate-Stop Distance Available': 'ASDA',
    'Airspeed Gain': 'ASPEEDG',
    'Airspeed Loss': 'ASPEEDL',
    'Asphalt': 'ASPH',
    'Actual Time of Arrival': 'ATA',
    'Actual Time of Departure': 'ATD',
    'Air Traffic Flow Management': 'ATFM',
    'Air Traffic Management': 'ATM',
    'At': 'ATP',
    'Attention': 'ATTN',
    'Aerodrome Traffic Zone': 'ATZ',
    'August': 'AUG',
    'Authorization': 'AUTH',
    'All Up Weight': 'AUW',
    'Auxiliary': 'AUX',
    'Available': 'AVBL',
    'Average': 'AVG',
    'Aviation Gasoline': 'AVGAS',
    'Advise At What Time Able': 'AWTA',
    'Airway': 'AWY',
    'Airways': 'AWYS',
    'Azimuth': 'AZM',
    'Braking Action': 'BA',
    'Beacon': 'BCN',
    'Broadcast': 'BCST',
    'Boundary': 'BDRY',
    'Before': 'BFR',
    'Building': 'BLDG',
    'Below Clouds': 'BLO',
    'Below': 'BLW',
    'Short': 'BRF',
    'Bearing': 'BRG',
    'Breaking': 'BRKG',
    'Between Layers': 'BTL',
    'Between': 'BTN',
    'Candela': 'CD',
    'Coordination': 'COOR',
    'Change Frequency To': 'CF',
    'Confirm': 'CFM',
    'Circling Guidance Light(s)': 'CGL',
    'Channel': 'CH',
    'Changed': 'CHG',
    'Near or Over Large Towns': 'CIT',
    'Civil': 'CIV',
    'Check': 'CK',
    'Centre Line': 'CL',
    'Calibration': 'CLBR',
    'Cloud': 'CLD',
    'Calling': 'CLG',
    'Climb-out Area': 'CLIMB-OUT',
    'Clearance': 'CLR',
    'Cleared': 'CLRD',
    'Closed': 'CLSD',
    'Climb': 'CMB',
    'Complete': 'CMPL',
    'Cancel': 'CNL',
    'Communications, Navigation And Surveillance': 'CNS',
    'Communications': 'COM',
    'Concrete': 'CONC',
    'Condition': 'COND',
    'Continuous': 'CONS',
    'Construction': 'CONST',
    'Continued': 'CONT',
    'Coordinates': 'COORD',
    'Change-over Point': 'COP',
    'Correction': 'COR',
    'At The Coast': 'COT',
    'Covered': 'COV',
    'Controller-pilot Data Link Communications': 'CPDLC',
    'Current Flight Plan': 'CPL',
    'Cyclic Redundancy Check': 'CRC',
    'Cruise': 'CRZ',
    'Climb To And Maintain': 'CTAM',
    'Contact': 'CTC',
    'Control': 'CTL',
    'Caution': 'CTN',
    'Control Zone': 'CTR',
    'Cockpit Voice Recorder': 'CVR',
    'Continuous Wave': 'CW',
    'Clearway': 'CWY',
    'Decision Altitude': 'DA',
    'Docking': 'DCKG',
    'Datum Crossing Point': 'DCP',
    'Direct Controller-pilot Communications': 'DCPC',
    'Direct': 'DCT',
    'December': 'DEC',
    'Degrees': 'DEG',
    'Departing': 'DEP',
    'Descend': 'DES',
    'Destination': 'DEST',
    'Distress Phase': 'DETRESFA',
    'Deviating': 'DEV',
    'Digital Flight Data Recorder': 'DFDR',
    'Distance From Touchdown Indicator': 'DFTI',
    'Decision Height': 'DH',
    'Diffuse': 'DIP',
    'Distance': 'DIST',
    'Divert': 'DIV',
    'Delay': 'DLA',
    'Daily': 'DLY',
    'Dangerous': 'DNG',
    'Domestic': 'DOM',
    'Depth': 'DPT',
    'Dead Reckoning': 'DR',
    'During': 'DRG',
    'Descend To And Maintain': 'DTAM',
    'Date-time Group': 'DTG',
    'Displaced Runway Threshold': 'DTHR',
    'Deteriorating': 'DTRT',
    'Dual Tandem Wheels': 'DTW',
    'This Is A Duplicate Message': 'DUPE',
    'Duration': 'DUR',
    'Doppler VOR': 'DVOR',
    'Dual Wheels': 'DW',
    'Expected Approach Time': 'EAT',
    'Eastbound': 'EB',
    'Elevation Differential Area': 'EDA',
    'Estimated Elapsed Time': 'EET',
    'Expect Further Clearance': 'EFC',
    'Emergency Location Beacon': 'ELBA',
    'Elevation': 'ELEV',
    'Extra Long Range': 'ELR',
    'Emission': 'EM',
    'Emergency': 'EMERG',
    'Stop-end': 'END',
    'East-north-east': 'ENE',
    'Engine': 'ENG',
    'En-route': 'ENR',
    'En-route Chart': 'ENRC',
    'Estimated Off-block Time': 'EOBT',
    'Equipment': 'EQPT',
    'Here': 'ER',
    'East-south-east': 'ESE',
    'Estimate': 'EST',
    'Estimated Time Of Arrival': 'ETA',
    'Estimated Time Of Departure': 'ETD',
    'Estimated Time Over Significant Point': 'ETO',
    'Every': 'EV',
    'Except': 'EXC',
    'Exercise': 'EXER',
    'Expect': 'EXP',
    'Extend': 'EXTD',
    'Facilities': 'FAC',
    'Final Approach Fix': 'FAF',
    'Facilitation of International Airtransport': 'FAL',
    'Final Approach Point': 'FAP',
    'Final Approach And Take-off Area': 'FATO',
    'Fax': 'FAX',
    'Light': 'FBL',
    'Forecast': 'FCST',
    'Friction Coefficient': 'FCT',
    'Flight Data Processing System': 'FDPS',
    'February': 'FEB',
    'Field': 'FLD',
    'Flashing': 'FLG',
    'Flares': 'FLR',
    'Flight': 'FLT',
    'Flights': 'FLTS',
    'Flight Check': 'FLTCK',
    'Fluctuating': 'FLUC',
    'Follow(s)': 'FLW',
    'Fly': 'FLY',
    'From': 'FM',
    'Flight Management System': 'FMS',
    'Flow Management Unit': 'FMU',
    'Final Approach': 'FNA',
    'Flight Path Alignment Point': 'FPAP',
    'Flight Plan': 'PLN',
    'Flight Plans': 'FPLS',
    'Feet Per Minute': 'FPM',
    'Flight Plan Route': 'FPR',
    'Fuel Remaining': 'FR',
    'Frequency': 'FREQ',
    'Friday': 'FRI',
    'Firing': 'FRNG',
    'Front': 'FRONT',
    'Frequent': 'FRQ',
    'Full Stop Landing': 'FSL',
    'Flight Service Station': 'FSS',
    'First': 'FST',
    'Fictitious Threshold Point': 'FTP',
    'Ground-to-air': 'G/A',
    'Ground-to-air and Air-to-ground': 'G/A/G',
    'GBAS Azimuth Reference Point': 'GARP',
    'Ground-based Augmentation System': 'GBAS',
    'Ground Controlled Approach': 'GCAJ',
    'General': 'GEN',
    'Geographic or True': 'GEO',
    'Ground Earth Station': 'GES',
    'Glider': 'GLD',
    'Ground Movement Chart': 'GMC',
    'Ground': 'GND',
    'Ground Check': 'GNDCK',
    'Glide Path': 'GP',
    'Grass landing area': 'GRASS',
    'Gravel': 'GRVL',
    'Geoid Undulation': 'GUND',
    '24 Hours': 'H24',
    'Helicopter Approach Path Indicator': 'HAPI',
    'Hazard Beacon': 'HBN',
    'Heading': 'HDG',
    'Helicopter': 'HEL',
    'Height': 'HOT',
    'Sunrise to Sunset': 'HJ',
    'Holding': 'HLDG',
    'Sunset to Sunrise': 'HN',
    'Service Available To Meet Operational Requirements': 'HO',
    'Holiday': 'HOL',
    'Hospital Aircraft': 'HOSP',
    'Hectopascal': 'HPA',
    'Hours': 'HRS',
    'Service Available During Hours Of Scheduled Operations': 'HS',
    'Hurricane': 'HURCN',
    'Heavy': 'HVY',
    'No Specific Working Hours': 'HX',
    'Higher': 'HYR',
    'Instrument Approach Chart': 'IAC',
    'Initial Approach Fix': 'IAF',
    'In And Out Of Clouds': 'IAO',
    'Instrument Approach Procedure': 'IAP',
    'Intersection Of Air Routes': 'IAR',
    'Identification Beacon': 'IBN',
    'Identifier': 'ID',
    'Identification': 'IDENT',
    'Identification Friend/Foe': 'IFF',
    'International General Aviation': 'IGA',
    'Inner Marker': 'IM',
    'Improving': 'IMPR',
    'Immediately': 'IMT',
    'Initial Approach': 'INA',
    'Inbound': 'INBD',
    'Uncertainty Phase': 'INCERFA',
    'Information': 'INFO',
    'Inoperative': 'INOP',
    'If Not Possible': 'INP',
    'In Progress': 'INPR',
    'Installation': 'INSTL',
    'Instrument': 'INSTR',
    'Intersection': 'INT',
    'Intersections': 'INTS',
    'International': 'INTL',
    'Interrogator': 'INTRG',
    'Interruption': 'INTRP',
    'Intensifying': 'INTSF',
    'Intensity': 'INTST',
    'International Standard Atmosphere': 'ISA',
    'January': 'JAN',
    'Jet stream': 'JTST',
    'July': 'JUL',
    'June': 'JUN',
    'Kilometres Per Hour': 'KMH',
    'Kilopascal': 'KPA',
    'Knots': 'KT',
    'Kilowatts': 'KW',
    'Inland': 'LAN',
    'Latitude': 'LAT',
    'Landing Distance Available': 'LDA',
    'Landing Distance Available, Helicopter': 'LDAH',
    'Landing': 'LDG',
    'Landing Direction Indicator': 'LDI',
    'Length': 'LEN',
    'Lighting': 'LGT',
    'Lighted': 'LGTD',
    'Light Intensity High': 'LIH',
    'Light Intensity Low': 'LIL',
    'Light Intensity Medium': 'LIM',
    'Localizer': 'LLZ',
    'Locator, Middle': 'LM',
    'Local Mean Time': 'LMT',
    'Long': 'LNG',
    'Locator, Outer': 'LO',
    'Located': 'LOG',
    'Longitude': 'LONG',
    'Long Range': 'LRG',
    'Limited': 'LTD',
    'Landing Threshold Point': 'LTP',
    'Leaving': 'LVE',
    'Level': 'LVL',
    'Layer': 'LYR',
    'Maximum Authorized Altitude': 'MAA',
    'Magnetic': 'MAG',
    'Maintenance': 'MAINT',
    'Aeronautical Maps and Charts': 'MAP',
    'Missed Approach Point': 'MAPT',
    'March': 'MAR',
    'Maximum': 'MAX',
    'May': 'MAY',
    'Microburst': 'MBST',
    'Minimum Crossing Altitude': 'MCA',
    'Modulated Continuous Wave': 'MCW',
    'Minimum Descent Altitude': 'MDA',
    'Minimum Descent Height': 'MDH',
    'Minimum En-route Altitude': 'MEA',
    'Minimum Eye Height Over Threshold': 'MEHT',
    'Meteorological': 'MET',
    'Mid-point': 'MID',
    'Military': 'MIL',
    'Minutes': 'MIN',
    'Marker Radio Beacon': 'MKR',
    'Microwave Landing System': 'MLS',
    'Middle Marker': 'MM',
    'Minimum': 'MNM',
    'Minimum Navigation Performance Specifications': 'MNPS',
    'Monitor': 'MNT',
    'Maintain': 'MNTN',
    'Military Operating Area': 'MOA',
    'Minimum Obstacle Clearance': 'MOC',
    'Moderate': 'MOD',
    'Monday': 'MON',
    'Minimum Operational Performance Standards': 'MOPS',
    'Movement': 'MOV',
    'Minimum Reception Altitude': 'MRA',
    'Medium Range': 'MRG',
    'ATS/MET Reporting Point': 'MRP',
    'Minus': 'MS',
    'Minimum Sector Altitude': 'MSA',
    'Minimum Safe Altitude Warning': 'MSAW',
    'Message': 'MSG',
    'Monopulse Secondary Surveillance Radar': 'MSSR',
    'Mountain': 'MT',
    'Metric Units': 'MTU',
    'Mountain Waves': 'MTW',
    'National AIS System Centre': 'NASC',
    'North Atlantic': 'NAT',
    'Navigation': 'NAV',
    'Northbound': 'NB',
    'Not Before': 'NBFR',
    'North-east': 'NE',
    'North-eastbound': 'NEB',
    'Negative': 'NEG',
    'Night': 'NGT',
    'None': 'NIL',
    'Normal': 'NML',
    'North-north-east': 'NNE',
    'North-north-west': 'NNW',
    'International NOTAM Office': 'NOF',
    'November': 'NOV',
    'Normal Operating Zone': 'NOZ',
    'Number': 'NR',
    'No Reply Heard': 'NRH',
    'National': 'NTL',
    'No Transgression Zone': 'NTZ',
    'North-west': 'NW',
    'North-westbound': 'NWB',
    'Next': 'NXT',
    'On Request': 'O/R',
    'Oceanic Area Control Centre': 'OAC',
    'Obstacle Assessment Surface': 'OAS',
    'Observe': 'OBS',
    'Obstacle': 'OBST',
    'Obstacles': 'OBSTS',
    'Oceanic Control Area': 'OCA',
    'Obstacle Clearance Height': 'OCH',
    'Obstacle Clearance Surface': 'OCS',
    'October': 'OCT',
    'Obstacle Free Zone': 'OFZ',
    'Originate': 'OGN',
    'Overhead': 'OHD',
    'Outer Marker': 'OM',
    'Control Indicated Is Operational Control': 'OPC',
    'Operational Meteorological': 'OPMET',
    'Open': 'OPN',
    'Operate': 'OPR',
    'Operations': 'OPS',
    'Order': 'ORD',
    'Ocean Station Vessel': 'OSV',
    'Outlook': 'OTLK',
    'On Top': 'OTP',
    'Organized Track System': 'OTS',
    'Outbound': 'OUBD',
    'Precision Approach': 'PA',
    'Precision Approach Lighting System': 'PALS',
    'Procedures for Air Navigation Services': 'PANS',
    'Precision Approach Radar': 'PAR',
    'Parallel': 'PARL',
    'Precision Approach Terrain Chart': 'PATC',
    'Passenger(s)': 'PAX',
    'Proceed': 'PCD',
    'Pilot-controlled Lighting': 'PCL',
    'Pavement Classification Number': 'PCN',
    'Pre-departure Clearance': 'PDC',
    'Procedure Design Gradient': 'PDG',
    'Performance': 'PER',
    'Permanent': 'PERM',
    'Pre-flight Information Bulletin': 'PIB',
    'Parachute Jumping Exercise': 'PJE',
    'Practice Low Approach': 'PLA',
    'Present Level': 'PLVL',
    'Prior Notice Required': 'PN',
    'Point Of No Return': 'PNR',
    'Persons On Board': 'POB',
    'Possible': 'POSS',
    'Plan Position Indicator': 'PPI',
    'Prior Permission Required': 'PPR',
    'Present Position': 'PPSN',
    'Primary': 'PRI',
    'Parking': 'PRKG',
    'Probability': 'PROB',
    'Procedure': 'PROC',
    'Provisional': 'PROV',
    'Plus': 'PS',
    'Passing': 'PSG',
    'Position': 'PSN',
    'Positions': 'PSNS',
    'Primary Surveillance Radar': 'PSR',
    'Pressure System(s)': 'PSYS',
    'Procedure Turn': 'PTN',
    'Polar Track Structure': 'PTS',
    'Power': 'PWR',
    'Quadrant': 'QUAD',
    'Rules of The Air and Air Traffic Services': 'RAC',
    'Runway Arresting Gear': 'RAG',
    'Runway Alignment Indicator': 'RAI',
    'Regional AIS System Centre': 'RASC',
    'Remote Altimeter Setting Source': 'RASS',
    'Rescue Boat': 'RB',
    'Reach Cruising Altitude': 'RCA',
    'Rescue Coordination Centre': 'RCC',
    'Radiocommunication Failure': 'RCF',
    'Reaching': 'RCH',
    'Runway Centre Line': 'RCL',
    'Runway Centre Line Light(s)': 'RCLL',
    'Recleared': 'RCLR',
    'Reference Datum Height': 'RDH',
    'Radial': 'RDL',
    'Radio': 'RDO',
    'Recent': 'RE',
    'Receiver': 'REC',
    'Runway Edge Light(s)': 'REDL',
    'Refer To': 'REF',
    'Registration': 'REG',
    'Runway End Light(s)': 'RENL',
    'Report': 'REP',
    'Requested': 'REQ',
    'Re-route': 'RERTE',
    'Runway End Safety Area': 'RESA',
    'Range (lights)': 'RG',
    'Right-hand Circuit': 'RHC',
    'Reclearance In Flight': 'RIF',
    'Right': 'RITE',
    'Report Leaving': 'RL',
    'Relay To': 'RLA',
    'Request Level Change En Route': 'RLCE',
    'Runway Lead-in Lighting System': 'RLLS',
    'Request Level Not Available': 'RLNA',
    'Radar Minimum Altitude Chart': 'RMAC',
    'Remark': 'RMK',
    'Radio Range': 'RNG',
    'Required Navigation Performance': 'RNP',
    'Rate Of Climb': 'ROC',
    'Rate Of Descent': 'ROD',
    'Route Forecast': 'ROFOR',
    'Receiving Only': 'RON',
    'Radar Position Indicator': 'RPI',
    'Repetitive Flight Plan': 'RPL',
    'Replaced': 'RPLC',
    'Radar Position Symbol': 'RPS',
    'Requirements': 'RQMNTS',
    'Request Flight Plan': 'RQP',
    'Request Supplementary Flight Plan': 'RQS',
    'Report Reaching': 'RR',
    'Rescue Sub-centre': 'RSC',
    'Runway Surface Condition': 'RSCD',
    'Responder Beacon': 'RSP',
    'En-route Surveillance Radar': 'RSR',
    'Route': 'RTE',
    'Routes': 'RTES',
    'Radiotelephone': 'RTF',
    'Radiotelegraph': 'RTG',
    'Runway Threshold Light(s)': 'RTHL',
    'Return': 'RTN',
    'Rejected Take-off Distance Available, Helicopter': 'RTODAH',
    'Return To Service': 'RTS',
    'Radioteletypewriter': 'RTT',
    'Runway Touchdown Zone Light(s)': 'RTZL',
    'Standard Regional Route Transmitting Frequencies': 'RUT',
    'Rescue Vessel': 'RV',
    'Reduced Vertical Separation Minimum': 'RVSM',
    'Runway': 'RWY',
    'Runways': 'RWYS',
    'Simple Approach Lighting System': 'SALS',
    'Sanitary': 'SAN',
    'As Soon As Possible': 'SAP',
    'Search and Rescue': 'SAR',
    'Standards and Recommended Practices': 'SARPS',
    'Saturday': 'SAT',
    'Satellite Communication': 'SATCOM',
    'Southbound': 'SB',
    'Satellite-based Augmentation System': 'SBAS',
    'Stand by': 'SDBY',
    'South-east': 'SE',
    'Sea': 'SEA',
    'South-eastbound': 'SEB',
    'Seconds': 'SEC',
    'Section': 'SECN',
    'Sector': 'SECT',
    'September': 'SEP',
    'Service': 'SER',
    'Severe': 'SEV',
    'Surface': 'SFC',
    'Signal': 'SGL',
    'Standard Instrument Departure': 'SID',
    'Selective Identification Feature': 'SIF',
    'Significant': 'SIG',
    'Simultaneous': 'SIMUL',
    'Schedule': 'SKED',
    'Speed Limiting Point': 'SLP',
    'Slow': 'SLW',
    'Surface Movement Control': 'SMC',
    'Surface Movement Radar': 'SMR',
    'Supplementary Flight Plan': 'SPL',
    'SAR Point Of Contact': 'SPOC',
    'Spot Wind': 'SPOT',
    'Sunrise': 'SR',
    'Surveillance Radar Approach': 'SRA',
    'Surveillance Radar Element Of Precision Approach Radar System': 'SRE',
    'Short Range': 'SRG',
    'Search and Rescue Region': 'SRR',
    'Secondary': 'SRY',
    'Sunset': 'SS',
    'South-south-east': 'SSE',
    'Secondary Surveillance Radar': 'SSR',
    'Supersonic Transport': 'SST',
    'South-south-west': 'SSW',
    'Straight-in Approach': 'STA',
    'Standard Instrument Arrival': 'STAR',
    'Standard': 'STD',
    'Station': 'STN',
    'Stationary': 'STNR',
    'Short Take-off and Landing': 'STOL',
    'Status': 'STS',
    'Stopway Light(s)': 'STWL',
    'Subject To': 'SUBJ',
    'Sunday': 'SUN',
    'Supplement': 'SUP',
    'Regional Supplementary Procedures Service Message': 'SUPPS',
    'Serviceable': 'SVCBL',
    'South-west': 'SW',
    'South-westbound': 'SWB',
    'Stopway': 'SWY',
    'Transition Altitude': 'TA',
    'Terminal Arrival Altitude': 'TAA',
    'Aerodrome Forecast': 'TAF',
    'Tail Wind': 'TAIL',
    'Terminal Area Surveillance Radar': 'TAR',
    'Taxi': 'TAX',
    'Tropical Cyclone Advisory Centre': 'TCAC',
    'Tornado': 'TDO',
    'Touchdown Zone': 'TDZ',
    'Technical Reason': 'TECR',
    'Temporarily': 'TEMPO',
    'Traffic': 'TFC',
    'Touch-and-go': 'TGL',
    'Taxiing Guidance System': 'TGS',
    'Threshold': 'THR',
    'Through': 'THRU',
    'Thursday': 'THU',
    'Traffic Information Broadcast By Aircraft': 'TIBA',
    'Until': 'TIL',
    'Until Past': 'TIP',
    'Take-off': 'TKOF',
    'Till': 'TL',
    'Touchdown And Lift-off Area': 'TLOF',
    'Terminal Control Area': 'TMA',
    'Turn Altitude': 'TNA',
    'Turn Height': 'TNH',
    'Top of Climb': 'TOC',
    'Take-off Distance Available': 'TODA',
    'Take-off Distance Available, Helicopter': 'TODAH',
    'Take-off Run Available': 'TORA',
    'Turning Point': 'TP',
    'Track': 'TR',
    'Temporary Reserved Airspace': 'TRA',
    'Transmitter': 'TRANS',
    'Transition Level': 'TRL',
    'Tuesday': 'TUE',
    'Turbulence': 'TURB',
    'Terminal VOR': 'TVOR',
    'Tower': 'TWR',
    'Taxiway': 'TWY',
    'Taxiway-link': 'TWYL',
    'Text': 'TXT',
    'Type of Aircraft': 'TYP',
    'Unserviceable': 'U/S',
    'Until Advised By': 'UAB',
    'Upper Area Control Centre': 'UAC',
    'Upper Air Route': 'UAR',
    'Until Further Notice': 'UFN',
    'Unable Higher Due Traffic': 'UHDT',
    'Upper Information Centre': 'UIC',
    'Upper Flight Information Region': 'UIR',
    'Ultra Long Range': 'ULR',
    'Unable': 'UNA',
    'Unable To Approve': 'UNAP',
    'Unlimited': 'UNL',
    'Unreliable': 'UNREL',
    'Upper Control Area': 'UTA',
    'Volcanic Ash Advisory Centre': 'VAAC',
    'Visual Approach Chart': 'VAC',
    'In Valleys': 'VAL',
    'Runway Control Van': 'VAN',
    'Visual-aural Radio Range': 'VAR',
    'Vicinity': 'VCY',
    'Vertical': 'VER',
    'Visibility': 'VIS',
    'Very Long Range': 'VLR',
    'Vertical Path Angle': 'VPA',
    'Variable': 'VRB',
    'By Visual Reference To The Ground': 'VSA',
    'Vertical Speed': 'VSP',
    'Vertical Take-off And Landing': 'VTOL',
    'World Aeronautical Chart': 'WAC',
    'World Area Forecast Centre': 'WAFC',
    'Westbound': 'WB',
    'Wing Bar Lights': 'WBAR',
    'Wind Direction Indicator': 'WDI',
    'Widespread': 'WDSPR',
    'Wednesday': 'WED',
    'Effective From': 'WEF',
    'Within': 'WI',
    'Width': 'WID',
    'Effective Immediately': 'WIE',
    'Will Comply': 'WILCO',
    'Wind': 'WIND',
    'Forecast Upper Wind And Temperature For Aviation': 'WINTEM',
    'Work In Progress': 'WIP',
    'Weaken': 'WKN',
    'West-north-west': 'WNW',
    'Without': 'WO',
    'Way-point': 'WPT',
    'Warning': 'WRNG',
    'West-south-west': 'WSW',
    'Weight': 'WT',
    'Worldwide Web': 'WWW',
    'Weather': 'WX',
    'Crossbar': 'XBAR',
    'Crossing': 'XNG',
    'Atmospherics': 'XS',
    'Yellow Caution Zone': 'YCZ',
    'Your': 'YR',
}